# Generated by Django 5.2.6 on 2025-09-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleName', models.CharField(max_length=200)),
                ('vehicleCategory', models.CharField(max_length=200)),
                ('vehicleBrand', models.CharField(max_length=200)),
                ('vehicleNumber', models.CharField(max_length=10)),
                ('vehicleColor', models.CharField(max_length=10)),
                ('vehicleManu', models.DateField(null=True)),
                ('vehiclePrice', models.FloatField(null=True)),
            ],
        ),
    ]
