# Generated by Django 5.2.6 on 2025-09-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAPIs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt', models.CharField(max_length=6)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
