# Generated by Django 5.2.6 on 2025-09-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAPIs', '0002_otpdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpdetails',
            name='email',
        ),
        migrations.AddField(
            model_name='otpdetails',
            name='mobileNumberVerified',
            field=models.BooleanField(default=False),
        ),
    ]
