# Generated by Django 5.2.6 on 2025-09-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAPIs', '0003_remove_otpdetails_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpdetails',
            old_name='opt',
            new_name='otp',
        ),
    ]
