# Generated by Django 5.2.6 on 2025-09-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAPIs', '0004_rename_opt_otpdetails_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=12)),
                ('lastName', models.CharField(max_length=12)),
                ('profilePicture', models.ImageField(upload_to='profilePhoto/')),
            ],
        ),
    ]
